language: python
python:
  - '2.7'

#we want a newer cppcheck, so use trusty
dist: trusty

sudo: false

cache:
  directories:
  - "~/.platformio"
  - "./.pioenvs"

addons:
  apt:
    packages:
    - cppcheck

install:
  - pip install -U platformio

script:
  - cppcheck --enable=warning src/main.cc -q --force -I src lib --include=lib/* --error-exitcode=1
  - platformio run -s

notifications:
  email: false